version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/resources/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: postgres
        update-types: ["version-update:semver-major"]
