_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: TV Finder
homepageEnabled: true
homepageGroup: Media
homepageIcon: sonarr
homepageName: Sonarr
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: sonarr.crt.house
ingName: sonarr
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: ''
name: sonarr
namespace: sonarr
pvc: false
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: sonarr
svcPortNum: 8989
upstreamURL: https://sonarr.tv/
url: https://github.com/charlesthomas/homelab-sonarr
