---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      dnsConfig:
        nameservers:
        - 10.43.0.10
      dnsPolicy: None
      initContainers:
      - name: cp-config
        image: alpine:latest
        resources: {}
        volumeMounts:
          - name: sonarr-config
            mountPath: /tmp/sonarr-config
          - name: sonarr
            mountPath: /config
        command:
          - cp
          - -v
          - /tmp/sonarr-config/config.xml
          - /config/config.xml
      containers:
      - name: sonarr
        image: sonarr
        imagePullPolicy: IfNotPresent
        ports:
        - name: sonarr
          containerPort: 8989
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Detroit"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: sonarr
          mountPath: /config
        - name: media
          mountPath: /mnt/media
        resources: {}
        readinessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: sonarr
        persistentVolumeClaim:
          claimName: sonarr
      - name: sonarr-config
        secret:
          secretName: sonarr-config
      - name: media
        nfs:
          path: /volume1/media
          server: 192.168.1.21
